---
title: "Aflevering"
output: pdf_document
date: "2026-05-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Library
```{r}
library(mlr3)
library(mlr3learners)
library(mlr3tuning)
library(mlr3mbo)
library(mlr3pipelines)
library(paradox)
library(readr)
library(tidyverse)
library(mlr3viz)
```

# Load data

```{r}
freMPL <- read_csv("freMPL.csv")

MPL_data <- subset(freMPL, select = -ClaimInd)
MPL_data$RecordEnd[is.na(MPL_data$RecordEnd)] <- as.Date("2005-01-01")
```

# Pre-processing

```{r}
# Creating a new data set where few observations are lumped together as "other" to avoid problems with test-observations that are not not seen in the training data
MPL_data_lump <- MPL_data

factor_cols <- names(MPL_data_lump)[sapply(MPL_data_lump, function(x) is.factor(x) || is.character(x))]

for (col in factor_cols) {
  MPL_data_lump[[col]] <- as.factor(MPL_data_lump[[col]])
  MPL_data_lump[[col]] <- fct_lump_min(MPL_data_lump[[col]], min = 10)
  MPL_data_lump[[col]] <- droplevels(MPL_data_lump[[col]])
}
```

```{r}
categorical_vars <- c("VehAge", "Gender", "MariStat", "SocioCateg", "VehUsage", "VehBody", "VehPrice", "VehEngine", "VehEnergy", "VehMaxSpeed", "VehClass", "Garage") # VehMax Speed should perhaps be converted to a numeric variable by taking eg the max number in the observations given interval
MPL_data_lump[categorical_vars] <- lapply(MPL_data_lump[categorical_vars], factor)
```



Skal det her med? 
```{r}
# VehAge is an ordered variable
freMPL$VehAge <- factor(freMPL$VehAge, levels = c("0", "1", "2", "3", "4", "5", "6-7", "8-9", "10+"))

# VehMaxSpeed is an ordered variable
freMPL$VehMaxSpeed <- factor(freMPL$VehMaxSpeed,
                             levels = c("1-130 km/h", "130-140 km/h", "140-150 km/h",
                                        "150-160 km/h", "160-170 km/h", "170-180 km/h", 
                                        "180-190 km/h", "190-200 km/h", "200-220 km/h",
                                        "220+ km/h"))
```
