---
title: "Partial linear regression"
author: "Ingelise Reffeldt"
date: "2026-05-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Library
```{r}
library(mlr3)
library(mlr3learners)
library(mlr3extralearners)
library(mlr3tuning)
library(mlr3mbo)
library(mlr3pipelines)
library(paradox)
library(readr)
library(tidyverse)
library(mlr3viz)
library(Metrics)
```

We start by making a matrix for the results we want 
```{r}
results <- matrix(0, nrow=5, ncol=3)
rownames(results) = c("LicAge", "Exposure","DrivAge","BonusMalus","VehPrice")
colnames(results) = c("regr.rmse", "regr.mae", "regr.rsq")
```

Now we make a model for each of our five chosen coefficient, where we focus on one off the coefficients and put all of the other together.

##LicAge
```{r}
task_amount_on_allother = as_task_regr(MPL_data_lump, target="ClaimAmount")$select(setdiff(names(freMPL), c("LicAge", "ClaimAmount")))
task_LicAge_on_allother = as_task_regr(MPL_data_lump, target="LicAge")$select(setdiff(names(freMPL), c("LicAge", "ClaimAmount")))

lrn_amount_on_allother_smooth = auto_tuner(
  tnr("random_search"),
  lrn(
    "regr.gam",
    formula=ClaimAmount ~ Exposure + RecordBeg + RecordEnd + VehAge + Gender + MariStat + SocioCateg + VehUsage + s(DrivAge) + HasKmLimit + s(BonusMalus) + VehBody + VehPrice + VehEngine+VehEnergy+VehMaxSpeed + VehClass + s(RiskVar) + Garage,
    gamma = to_tune(1,1e3,logscale=TRUE),
    select = to_tune(c(TRUE, FALSE)),
    drop.unused.levels=FALSE # Default is TRUE, but this may cause errors if splits are unlucky
  ),
  measure = msr("regr.mse"),
  resampling = rsmp("cv", folds=2),
  terminator = trm("evals", n_evals=10)
)
lrn_LicAge_on_allother_smooth = auto_tuner(
  tnr("random_search"),
  lrn(
    "regr.gam",
    formula=LicAge ~ Exposure + RecordBeg + RecordEnd + VehAge + Gender + MariStat + SocioCateg + VehUsage + s(DrivAge) + HasKmLimit + s(BonusMalus) + VehBody + VehPrice + VehEngine+VehEnergy+VehMaxSpeed + VehClass + s(RiskVar) + Garage,
    gamma = to_tune(1,1e3,logscale=TRUE),
    select = to_tune(c(TRUE, FALSE)),
    drop.unused.levels=FALSE # Default is TRUE, but this may cause errors if splits are unlucky
  ),
  measure = msr("regr.mse"),
  resampling = rsmp("cv", folds=2),
  terminator = trm("evals", n_evals=10)
)

cross_fit = function(task, learner, K){
  set.seed(2026)
  outer_resampling = rsmp("cv", folds=K)
  rr = resample(task, learner, outer_resampling)
  pred = rr$prediction() 
  pred$truth - pred$response
}

amount_residuals_smooth = cross_fit(task_amount_on_allother, lrn_amount_on_allother_smooth, K=2)
LicAge_residuals_smooth = cross_fit(task_LicAge_on_allother, lrn_LicAge_on_allother_smooth, K=2)

lm_amount_on_LicAge_smooth = lm(amount_residuals_smooth ~ LicAge_residuals_smooth)

results[1,] <- c(sqrt(mean(lm_amount_on_LicAge_smooth$residuals^2)),
mae(MPL_data_lump$ClaimAmount, predict(lm_amount_on_LicAge_smooth)),
summary(lm_amount_on_LicAge_smooth)$r.squared)
```
##Exposure 
```{r}
task_amount_on_allother = as_task_regr(MPL_data_lump, target="ClaimAmount")$select(setdiff(names(freMPL), c("Exposure", "ClaimAmount")))
task_Exposure_on_allother = as_task_regr(MPL_data_lump, target="Exposure")$select(setdiff(names(freMPL), c("Exposure", "ClaimAmount")))

lrn_amount_on_allother_smooth = auto_tuner(
  tnr("random_search"),
  lrn(
    "regr.gam",
    formula=ClaimAmount ~ LicAge + RecordBeg + RecordEnd + VehAge + Gender + MariStat + SocioCateg + VehUsage + s(DrivAge) + HasKmLimit + s(BonusMalus) + VehBody + VehPrice + VehEngine+VehEnergy+VehMaxSpeed + VehClass + s(RiskVar) + Garage,
    gamma = to_tune(1,1e3,logscale=TRUE),
    select = to_tune(c(TRUE, FALSE)),
    drop.unused.levels=FALSE # Default is TRUE, but this may cause errors if splits are unlucky
  ),
  measure = msr("regr.mse"),
  resampling = rsmp("cv", folds=2),
  terminator = trm("evals", n_evals=10)
)
lrn_Exposure_on_allother_smooth = auto_tuner(
  tnr("random_search"),
  lrn(
    "regr.gam",
    formula=Exposure ~ LicAge + RecordBeg + RecordEnd + VehAge + Gender + MariStat + SocioCateg + VehUsage + s(DrivAge) + HasKmLimit + s(BonusMalus) + VehBody + VehPrice + VehEngine+VehEnergy+VehMaxSpeed + VehClass + s(RiskVar) + Garage,
    gamma = to_tune(1,1e3,logscale=TRUE),
    select = to_tune(c(TRUE, FALSE)),
    drop.unused.levels=FALSE # Default is TRUE, but this may cause errors if splits are unlucky
  ),
  measure = msr("regr.mse"),
  resampling = rsmp("cv", folds=2),
  terminator = trm("evals", n_evals=10)
)

amount_residuals_smooth = cross_fit(task_amount_on_allother, lrn_amount_on_allother_smooth, K=2)
Exposure_residuals_smooth = cross_fit(task_Exposure_on_allother, lrn_Exposure_on_allother_smooth, K=2)

lm_amount_on_Exposure_smooth = lm(amount_residuals_smooth ~ Exposure_residuals_smooth)

results[2,] <- c(sqrt(mean(lm_amount_on_Exposure_smooth$residuals^2)),
mae(MPL_data_lump$ClaimAmount, predict(lm_amount_on_Exposure_smooth)),
summary(lm_amount_on_Exposure_smooth)$r.squared)
```
##DrivAge
```{r}
task_amount_on_allother = as_task_regr(MPL_data_lump, target="ClaimAmount")$select(setdiff(names(freMPL), c("DrivAge", "ClaimAmount")))
task_DrivAge_on_allother = as_task_regr(MPL_data_lump, target="DrivAge")$select(setdiff(names(freMPL), c("DrivAge", "ClaimAmount")))

lrn_amount_on_allother_smooth = auto_tuner(
  tnr("random_search"),
  lrn(
    "regr.gam",
    formula=ClaimAmount ~ LicAge + Exposure + RecordBeg + RecordEnd + VehAge + Gender + MariStat + SocioCateg + VehUsage + HasKmLimit + s(BonusMalus) + VehBody + VehPrice + VehEngine+VehEnergy+VehMaxSpeed + VehClass + s(RiskVar) + Garage,
    gamma = to_tune(1,1e3,logscale=TRUE),
    select = to_tune(c(TRUE, FALSE)),
    drop.unused.levels=FALSE # Default is TRUE, but this may cause errors if splits are unlucky
  ),
  measure = msr("regr.mse"),
  resampling = rsmp("cv", folds=2),
  terminator = trm("evals", n_evals=10)
)
lrn_DrivAge_on_allother_smooth = auto_tuner(
  tnr("random_search"),
  lrn(
    "regr.gam",
    formula=DrivAge ~ LicAge + Exposure + RecordBeg + RecordEnd + VehAge + Gender + MariStat + SocioCateg + VehUsage + HasKmLimit + s(BonusMalus) + VehBody + VehPrice + VehEngine+VehEnergy+VehMaxSpeed + VehClass + s(RiskVar) + Garage,
    gamma = to_tune(1,1e3,logscale=TRUE),
    select = to_tune(c(TRUE, FALSE)),
    drop.unused.levels=FALSE # Default is TRUE, but this may cause errors if splits are unlucky
  ),
  measure = msr("regr.mse"),
  resampling = rsmp("cv", folds=2),
  terminator = trm("evals", n_evals=10)
)

amount_residuals_smooth = cross_fit(task_amount_on_allother, lrn_amount_on_allother_smooth, K=2)
DrivAge_residuals_smooth = cross_fit(task_DrivAge_on_allother, lrn_DrivAge_on_allother_smooth, K=2)

lm_amount_on_DrivAge_smooth = lm(amount_residuals_smooth ~ DrivAge_residuals_smooth)

results[3,] <- c(sqrt(mean(lm_amount_on_DrivAge_smooth$residuals^2)),
mae(MPL_data_lump$ClaimAmount, predict(lm_amount_on_DrivAge_smooth)),
summary(lm_amount_on_DrivAge_smooth)$r.squared)
```
##BonusMalus
```{r}
task_amount_on_allother = as_task_regr(MPL_data_lump, target="ClaimAmount")$select(setdiff(names(freMPL), c("BonusMalus", "ClaimAmount")))
task_BonusMalus_on_allother = as_task_regr(MPL_data_lump, target="BonusMalus")$select(setdiff(names(freMPL), c("BonusMalus", "ClaimAmount")))

lrn_amount_on_allother_smooth = auto_tuner(
  tnr("random_search"),
  lrn(
    "regr.gam",
    formula=ClaimAmount ~ LicAge + Exposure + RecordBeg + RecordEnd + VehAge + Gender + MariStat + SocioCateg + VehUsage + s(DrivAge) + HasKmLimit + VehBody + VehPrice + VehEngine+VehEnergy+VehMaxSpeed + VehClass + s(RiskVar) + Garage,
    gamma = to_tune(1,1e3,logscale=TRUE),
    select = to_tune(c(TRUE, FALSE)),
    drop.unused.levels=FALSE # Default is TRUE, but this may cause errors if splits are unlucky
  ),
  measure = msr("regr.mse"),
  resampling = rsmp("cv", folds=2),
  terminator = trm("evals", n_evals=10)
)
lrn_BonusMalus_on_allother_smooth = auto_tuner(
  tnr("random_search"),
  lrn(
    "regr.gam",
    formula=BonusMalus ~ LicAge + Exposure + RecordBeg + RecordEnd + VehAge + Gender + MariStat + SocioCateg + VehUsage + s(DrivAge) + HasKmLimit + VehBody + VehPrice + VehEngine+VehEnergy+VehMaxSpeed + VehClass + s(RiskVar) + Garage,
    gamma = to_tune(1,1e3,logscale=TRUE),
    select = to_tune(c(TRUE, FALSE)),
    drop.unused.levels=FALSE # Default is TRUE, but this may cause errors if splits are unlucky
  ),
  measure = msr("regr.mse"),
  resampling = rsmp("cv", folds=2),
  terminator = trm("evals", n_evals=10)
)

amount_residuals_smooth = cross_fit(task_amount_on_allother, lrn_amount_on_allother_smooth, K=2)
BonusMalus_residuals_smooth = cross_fit(task_BonusMalus_on_allother, lrn_BonusMalus_on_allother_smooth, K=2)

lm_amount_on_BonusMalus_smooth = lm(amount_residuals_smooth ~ BonusMalus_residuals_smooth)

results[4,] <- c(sqrt(mean(lm_amount_on_BonusMalus_smooth$residuals^2)),
mae(MPL_data_lump$ClaimAmount, predict(lm_amount_on_BonusMalus_smooth)),
summary(lm_amount_on_BonusMalus_smooth)$r.squared)
```
##VehPrice 
```{r}
MPL_data_lump$VehPrice <- as.numeric(MPL_data_lump$VehPrice) #Can't have factor as a response variable

task_amount_on_allother = as_task_regr(MPL_data_lump, target="ClaimAmount")$select(setdiff(names(freMPL), c("VehPrice", "ClaimAmount")))
task_VehPrice_on_allother = as_task_regr(MPL_data_lump, target="VehPrice")$select(setdiff(names(freMPL), c("VehPrice", "ClaimAmount")))

lrn_amount_on_allother_smooth = auto_tuner(
  tnr("random_search"),
  lrn(
    "regr.gam",
    formula=ClaimAmount ~ LicAge + Exposure + RecordBeg + RecordEnd + VehAge + Gender + MariStat + SocioCateg + VehUsage + s(DrivAge) + HasKmLimit + s(BonusMalus) + VehBody + VehEngine+VehEnergy+VehMaxSpeed + VehClass + s(RiskVar) + Garage,
    gamma = to_tune(1,1e3,logscale=TRUE),
    select = to_tune(c(TRUE, FALSE)),
    drop.unused.levels=FALSE # Default is TRUE, but this may cause errors if splits are unlucky
  ),
  measure = msr("regr.mse"),
  resampling = rsmp("cv", folds=2),
  terminator = trm("evals", n_evals=10)
)
lrn_VehPrice_on_allother_smooth = auto_tuner(
  tnr("random_search"),
  lrn(
    "regr.gam",
    formula=VehPrice ~ LicAge + Exposure + RecordBeg + RecordEnd + VehAge + Gender + MariStat + SocioCateg + VehUsage + s(DrivAge) + HasKmLimit + s(BonusMalus) + VehBody + VehEngine+VehEnergy+VehMaxSpeed + VehClass + s(RiskVar) + Garage,
    gamma = to_tune(1,1e3,logscale=TRUE),
    select = to_tune(c(TRUE, FALSE)),
    drop.unused.levels=FALSE # Default is TRUE, but this may cause errors if splits are unlucky
  ),
  measure = msr("regr.mse"),
  resampling = rsmp("cv", folds=2),
  terminator = trm("evals", n_evals=10)
)

amount_residuals_smooth = cross_fit(task_amount_on_allother, lrn_amount_on_allother_smooth, K=2)
VehPrice_residuals_smooth = cross_fit(task_VehPrice_on_allother, lrn_VehPrice_on_allother_smooth, K=2)

lm_amount_on_VehPrice_smooth = lm(amount_residuals_smooth ~ VehPrice_residuals_smooth)

results[5,] <- c(sqrt(mean(lm_amount_on_VehPrice_smooth$residuals^2)),
mae(MPL_data_lump$ClaimAmount, predict(lm_amount_on_VehPrice_smooth)),
summary(lm_amount_on_VehPrice_smooth)$r.squared)

MPL_data_lump$VehPrice <- as.factor(MPL_data_lump$VehPrice) #Making it a factor again for later
```